language: r
warnings_are_errors: false
r_github_packages:
#  - jimhester/covr
env:
  global:
    secure: kGuHTlqPL81AoOy8f4VmVLZygddxUatdxu0ErFABM24d05Q2Vb3XpI5njAbngYqOYG+2qBvEUPEFbA45moxcO3spwG/ObVNvzuH6nfynv3y/I+E/+gpf+7nHtFdwbRt4rSFtnoy0TqAsDlX/ST7qnn3uQf2cf9VqENiJfM9I36I=
after_success:
# - Rscript -e 'library(covr);coveralls()'
 - mv j.misc*.tar.gz j.misc.tar.gz
 - Rscript -e 'devtools::install()'
 - Rscript -e 'library(j.misc);github_release(repo = "j.misc", username = "mikejiang", release_tag = "linux", verbose())'

notifications:
  email:
    on_success: change
    on_failure: change
